config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root 'pages#home'
  get 'dashboard' => "pages#dashboard"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Book do |book|
        book.try(:user) == user
      end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image
  has_attached_file :resource
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!, only: [:dashboard]

  def home
    if current_user
      redirect_to books_path
    end
  end

  def dashboard
    @books = current_user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to book_path(book) do %>
<%= image_tag "book.jpg", class: "img-responsive" %>
<% end %>

<div class="caption">
<p><strong><%= link_to book.name, book_path(book) %></strong></p>
<p>$<%= book.price.to_f / 100 %></p>
</div>
</div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :author %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :availability, required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">

<%= render @books %>

</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="container">
<div class="row">
 
<div class="col-md-6">
<%= image_tag "book.jpeg", class: "img-responsive" %>
</div>

<div class="col-md-6">
<h3><%= @book.name %> by <%= @book.author %></h3>
<p class="justify"><%= @book.description %></p>
<h4 class="text-right">$<%= @book.price.to_f / 100 %></h4>
</div>
 
</div>
</div>
 
<%= link_to "Edit", edit_book_path(@book)  %>
<%= link_to "Back", book_path  %>

app/views/layouts/_header.html.erb
<header>
  
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">eLibrary</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Books", books_path %></li>

          <% if current_user %>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        
        <ul class="nav navbar-nav">
          <li><a href="#">Link</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estuk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

<% flash.each do |type, message| %>
<div class="alert alert-info fade-in">
<button class="close" data-dismiss="alert">x</button>
<%= message %>
</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
<h1 class="text-center">Dashboard</h1>
  <div class="col-md-4">
    <h3 class="text-center">
      Books <%= link_to "New Book", new_book_path, class: "btn btn-primary bt-sm"  %>
    </h3>
    <table class="table">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Available</th>  
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %> 
          <tr>
            <td><%= book.id %></td>
            <td><%= link_to book.name, book_path(book) %></td>
            <td><%= book.availability %></td>
            <td><%= link_to "Edit", edit_book_path(book) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
  <div class="col-md-4">
    <h3 class="text-center">
      Purchased
    </h3>
  </div>
  <div class="col-md-4">
    <h3 class="text-center">
      Sales
    </h3>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  
  <div class="jumbotron">
  <h1>Welcome to our store</h1>
  <p>The largest online Digital Books Store</p>
  <%= link_to "Books", books_path, class: "btn btn-primary btn-block" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-block" %>
  </div>
</div>